# Generated by Django 4.0.4 on 2024-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_active_teacher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='teachers/cvs'),
        ),
    ]
