# Generated by Django 4.0.4 on 2024-02-24 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=datetime.date(2024, 2, 24))),
                ('end_date', models.DateField(default=datetime.date(2024, 2, 24))),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
