# Generated by Django 4.0.4 on 2024-02-26 23:33

import courses.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 2, 26), validators=[courses.models.validate_end_date_greater_than_start_date]),
        ),
    ]
